# Generated by Django 4.2.1 on 2025-05-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_family_familymembership_familyjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_change_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_change_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password_change_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password_change_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password_recovery_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='password_recovery_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
