# Generated by Django 4.2.1 on 2025-05-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_personalfolder_personaldocument_familyfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familydocument',
            name='recognized_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldocument',
            name='recognized_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
