from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
    path('katya/', views.katyaa),
    path('api/register/', views.RegisterView.as_view(), name='register'),
    path('api/confirm/', views.ConfirmEmailView.as_view(), name='confirm-email'),
    path('api/login/', views.LoginView.as_view(), name='login'),
    path('api/profile/', views.UserProfileView.as_view(), name='profile'),
    path('api/email_change/', views.RequestEmailChangeView.as_view(), name='email_change'),
    path('api/email_change_confirm/', views.ConfirmEmailChangeView.as_view(), name='email_change_confirm'),
    path('api/password_change/', views.RequestPasswordChangeView.as_view(), name='password_change'),
    path('api/password_change_confirm/', views.ConfirmPasswordChangeView.as_view(), name='password_change_confirm'),
    path('api/password_recovery/', views.PasswordRecoveryRequestView.as_view(), name='password_recovery'),
    path('api/password_recovery_confirm/', views.PasswordRecoveryConfirmView.as_view(), name='password_recovery_confirm'),
    path('api/edit_name/', views.EditNameView.as_view(), name='edit_name'),
    path('api/create_family/', views.CreateFamilyView.as_view(), name='create_family'),
    path('api/user_families/', views.UserFamiliesView.as_view(), name='user_families'),
    path('api/join_family/', views.JoinFamilyView.as_view(), name='join_family'),
    path('api/list_join/', views.ListJoinRequestsView.as_view(), name='list_join'),
    path('api/handle_join/', views.HandleJoinRequestView.as_view(), name='handle_join'),
    path('api/leave/', views.LeaveFamilyView.as_view(), name='leave'),
    path('api/family_detail/', views.FamilyDetailView.as_view(), name='family_detail'),
    path('api/transfer_owner/', views.TransferOwnershipView.as_view(), name='transfer_owner'),
    path('api/remove_member/', views.RemoveMemberView.as_view(), name='remove_member'),
    path('api/change_family_password/', views.ChangeFamilyPasswordView.as_view(), name='change_family_password'),
    path('api/logout/', views.LogoutView.as_view(), name='logout'),
    path('api/upload_personal_document/', views.UploadPersonalDocumentView.as_view(), name='upload_personal_document'),
    path('api/create_personal_folder/', views.CreatePersonalFolderView.as_view(), name='create_personal_folder'),
    path('api/folders/<int:folder_id>/',  views.PersonalFolderDetailView.as_view(), name='folder-detail'),
    path('api/familyfolders/',  views.FamilyFolderDetailView.as_view(), name='familyfolder-detail'),
    path('api/personal_presigned_url/', views.GetPresignedDownloadLinkView.as_view(), name='personal_presigned_url'),
    path('api/personal_storage/', views.PersonalStorageView.as_view(), name='personal_storage'),
    path('api/family_storage/', views.FamilyStorageView.as_view(), name='family_storage'),
    path('api/share_personal_document/', views.SharePersonalDocumentWithFamilyView.as_view(), name='share_personal_document'),
    path('api/share_personal_folder/', views.SharePersonalFolderWithFamilyView.as_view(), name='share_personal_folder'),
    path('api/upload_family_document/', views.UploadFamilyDocumentView.as_view(), name='upload_family_document'),
    path('api/create_family_folder/', views.CreateFamilyFolderView.as_view(), name='create_family_folder'),
    path('api/update_personal_document/', views.UpdatePersonalDocumentView.as_view(), name='update_personal_document'),
    path('api/delete_personal_document/', views.DeletePersonalDocumentView.as_view(), name='delete_personal_document'),
    path('api/personal_ocr/', views.OCRTextExtractionView.as_view(), name='personal_ocr'),
    path('api/translate_doc/', views.TranslateDocumentView.as_view(), name='translate_doc'),
    path('api/family_presigned_url/', views.FamilyDocumentPresignedUrlView.as_view(), name='family_presigned_url'),
    path('api/duplicate_doc/', views.DuplicateDocumentView.as_view(), name='duplicate_doc'),
    path('api/duplicate_family_doc/', views.DuplicateFamilyDocumentView.as_view(), name='duplicate_family_doc'),
    path('api/family_ocr/', views.FamilyOCRTextExtractionView.as_view(), name='family_ocr'),
]
